### ISSUE TITLE
ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF

### ISSUE THREAD

**Issue by fishermanG** [aeleos/cloudflared#14] opened 2021-09-02 07:12 UTC
Heyo

Thanks for the amazing guide. Now I can close off all the exposed 80 and 443 ports. Everything works fine e.g. multiple domains 

But.. the docker log is flooded with this

2021-09-01T14:33:19Z INF Starting metrics server on 127.0.0.1:34395/metrics
2021-09-01T14:33:20Z INF Connection c0a8d328-a652-461d-bfc8-535d9c91e56d registered connIndex=0 location=SEA
2021-09-01T14:33:21Z INF Connection 6b41f4fa-d0c0-48bb-83e8-23d81a31d4fa registered connIndex=1 location=HKG
2021-09-01T14:33:22Z INF Connection 62a34012-8ed3-4325-a261-a19811f29a9c registered connIndex=2 location=SEA
2021-09-01T14:33:23Z INF Connection acdd26d8-0047-4a1e-97bc-151c4fee13b9 registered connIndex=3 location=HKG
2021-09-01T14:34:09Z ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=687f37bd84af59ce-IAD originService=https://192.168.1.11:18443

2021-09-01T14:34:10Z ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=687f37c6a4be212d-SJC originService=https://192.168.1.11:18443

2021-09-01T14:37:03Z ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=687f3bff16f52f55-DFW originService=https://192.168.1.11:18443

Any idea?

**Comment by martinkeat** [comment] 2021-09-14 15:42
Just setup cloudflareds myself - same issue.

**Comment by aeleos** [comment] 2021-09-24 21:49
@fishermanG @martinkeat I also see these logs in general, and my understanding is that it isn't a problem. I haven't figured out what causes it but I haven't found anything that is broken so my assumption is that it is fine.

**Comment by aeleos** [comment] 2021-09-30 00:24
Closing this for now, if someone knows the root cause or a fix for this just make another issue

**Closed by aeleos** 2021-09-30 00:24 UTC

**Comment by bolavefasfas** [comment] 2022-02-07 17:25
> 

thanks buddy it is working for me also now i was pissed coudnt make it work for weeks and what does notlsverify actually means ? does it means that the traffic is unencrited from my server to cloudflares server ?? so someting else

**Comment by GeoSnipes** [comment] 2022-03-04 20:09
https://docs.ibracorp.io/cloudflare-tunnel/#certificate-not-valid-for-any-names

**Comment by darshanv237** [comment] 2023-06-28 05:37
Even I am facing the issue, i also notlsverify and set it true but still facing the issue

**Comment by darshanv237** [comment] 2023-06-28 05:40
2023-06-28T05:39:41Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 192.168.29.254:443: connect: connection refused" connIndex=0 dest=https://ssh.titancloud.cloud/ event=0 ip=198.41.200.23 type=ws

I am geeting this error

**Comment by raymond2030** [comment] 2025-07-18 12:25
2025-07-18T11:28:57Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:80: connect: connection refused" connIndex=1 event=1 ingressRule=0 originService=http://localhost:80
2025-07-18T11:28:57Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:80: connect: connection refused" connIndex=1 dest=https://superleis.dpdns.org/ event=0 ip=198.41.200.63 type=http
 ubuntu use docker method ,err displayed, can not reach the host. how to fix it ?
